##
# Circle CI 2.0 configuration
#
##
version: 2.1

orbs:
  docker: circleci/docker@2.8.1

jobs:
  run-tests:
    docker:
      - image: particleflux/circleci-docker-dgoss:5.0.0
    environment:
      # fixes a permission issue on Circle 2.0
      # see https://github.com/aelsabbahy/goss/issues/305#issuecomment-353122840
      GOSS_FILES_STRATEGY: cp

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run image tests
          command: |
            mkdir build

            echo "Building docker image..."
            docker build -t "test-image" . | tee "build/docker-build.log"

            cd tests
            dgoss run -Pit test-image bash

      - store_artifacts:
          path: build

workflows:
  version: 2
  workflow:
    jobs:
      - run-tests:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/

      # on master, only publish version tagged with commit
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - run-tests
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

      # on tags, publish tagged image & update latest
      - docker/publish:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - run-tests
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest,$CIRCLE_TAG

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run-tests
